[package]
name = "counter-gas-v2"
version = "1.0.0"
authors = []

[addresses]
my_addr="0xbea0c86684c839174030bc6b8a518cd1eb22baf8b509fdcf570a5911bebd4ffa"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

